# Generated by Django 2.2.28 on 2023-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cvbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xcdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvbvnnf', models.BigIntegerField()),
                ('eteyry', models.BigIntegerField()),
            ],
        ),
    ]
